### PR TITLE
[9.12] Make bootctrl compile for SODP

### PR DESCRIPTION
**Pull request by MarijnS95**
See individual commits for details. Also, CC https://github.com/sonyxperiadev/bug_tracker/issues/740.

Note that my branch is based on 9.14. Different commits/history tree, but there's no `diff` between the two :sweat_smile:. Shall we reference 9.14 for niceties?

### CODE REVIEW

**Comment by jerpelea** [comment]
I will duplicate the branch once we have the patches in

**Comment by MarijnS95** [comment]
I think we can just rename to 9.14 or keep using 9.12, no need to duplicate when the contents are identical.

**Comment by jerpelea** [comment]
9.14 will change in the future

**Comment by MarijnS95** [comment]
We can split at that point, but I really doubt that'll ever happen. There can be no breaking changes at least, just minor tag updates.

**Comment by jerpelea** [comment]
cherry-picked

**Pull request closed without merging**
